#!/bin/sh

# install necessary programs [append your favorites]
pkg_add openvpn dnscrypt-proxy vim mpv unzip sct wpa_supplicant dmenu firefox i3 st wget powerline-fonts

# configure X11

echo '# June 1st, 2017

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# if we have private ssh key(s), start ssh-agent and add the key(s)
id1=$HOME/.ssh/identity
id2=$HOME/.ssh/id_dsa
id3=$HOME/.ssh/id_rsa
id4=$HOME/.ssh/id_ecdsa
id5=$HOME/.ssh/id_ed25519

if [ -z "$SSH_AGENT_PID" ];
then
 if [ -x /usr/bin/ssh-agent ] && [ -f $id1 -o -f $id2 -o -f $id3 -o -f $id4 -o -f $id5 ];
 then
  eval `ssh-agent -s`
  ssh-add < /dev/null
 fi
fi

if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
	eval `dbus-launch --sh-syntax --exit-with-session`
fi


# start some nice programs
xsetroot -solid gray40 &
exec i3

if [ "$SSH_AGENT_PID" ]; then
 ssh-add -D < /dev/null
 eval `ssh-agent -s -k`
fi
' > .xinitrc

# configure dns to point to unbound

echo 'nameserver 127.0.0.1' > /etc/resolv.conf
chflags uchg /etc/resolv.conf

# creat redundant service

cp /etc/rc.d/dnscrypt_proxy /etc/rc.d/dnscrypt_proxy2

# configure boot
#dnscrypt_proxy_flags=-E -m1 -R dnscrypt.eu-nl -a 127.0.0.1:40

echo 'apmd_flags="-A"
dnscrypt_proxy_flags=-E -m1 -R dnscrypt.eu-dk -a 127.0.0.1:41
dnscrypt_proxy2_flags=-E -m1 -R ns0.dnscrypt.is -a 127.0.0.1:40
openvpn_enable="YES"
openvpn_if="tun"
pkg_scripts=dnscrypt_proxy2 dnscrypt_proxy
sshd_flags=NO
unbound_flags=-c /etc/unbound.conf' > /etc/rc.conf.local

# configure unbound to point to redundant dnscrpyt

echo 'server:
	interface: 127.0.0.1
	do-ip6: no
	access-control: 127.0.0.1/8 allow
	do-not-query-localhost: no
	hide-identity: yes
	hide-version: yes

	private-address: 10.0.0.0/8
	private-address: 172.16.0.0/12
	private-address: 192.168.0.0/16
forward-zone:
	name: "."
	forward-addr: 127.0.0.1@40
	forward-addr: 127.0.0.1@41' > /etc/unbound.conf

# configure dhclient.conf
echo 'send host-name "localhost";' > /etc/dhclient.conf

echo '# $OpenBSD: login.conf,v 1.7 2016/06/26 20:32:31 tedu Exp $

#
# Sample login.conf file.  See login.conf(5) for details.
#

#
# Standard authentication styles:
#
# passwd	Use only the local password file
# chpass	Do not authenticate, but change users password (change
#		the YP password if the user has one, else change the
#		local password)
# lchpass	Do not login; change users local password instead
# radius	Use radius authentication
# reject	Use rejected authentication
# skey		Use S/Key authentication
# activ		ActivCard X9.9 token authentication
# crypto	CRYPTOCard X9.9 token authentication
# snk		Digital Pathways SecureNet Key authentication
# tis		TIS Firewall Toolkit authentication
# token		Generic X9.9 token authentication
# yubikey	YubiKey authentication
#

# Default allowed authentication styles
auth-defaults:auth=passwd,skey:

# Default allowed authentication styles for authentication type ftp
auth-ftp-defaults:auth-ftp=passwd:

#
# The default values
# To alter the default authentication types change the line:
#	:tc=auth-defaults:\
# to be read something like: (enables passwd, "myauth", and activ)
#	:auth=passwd,myauth,activ:\
# Any value changed in the daemon class should be reset in default
# class.
#
default:\
	:path=/usr/bin /bin /usr/sbin /sbin /usr/X11R6/bin /usr/local/bin /usr/local/sbin:\
	:umask=022:\
	:datasize-max=2048M:\
	:datasize-cur=2048M:\
	:maxproc-max=256:\
	:maxproc-cur=128:\
	:openfiles-cur=1024:\
	:stacksize-cur=16M:\
	:localcipher=blowfish,a:\
	:tc=auth-defaults:\
	:tc=auth-ftp-defaults:

#
# Settings used by /etc/rc and root
# This must be set properly for daemons started as root by inetd as well.
# Be sure reset these values back to system defaults in the default class!
#
daemon:\
	:ignorenologin:\
	:datasize=infinity:\
	:maxproc=infinity:\
	:openfiles-cur=128:\
	:stacksize-cur=8M:\
	:localcipher=blowfish,a:\
	:tc=default:

#
# Staff have fewer restrictions and can login even when nologins are set.
#
staff:\
	:datasize-cur=2048M:\
	:datasize-max=infinity:\
	:maxproc-max=512:\
	:maxproc-cur=256:\
	:ignorenologin:\
	:requirehome@:\
	:tc=default:

#
# Authpf accounts get a special motd and shell
#
authpf:\
	:welcome=/etc/motd.authpf:\
	:shell=/usr/sbin/authpf:\
	:tc=default:

#
# Building ports with DPB uses raised limits
#
pbuild:\
	:datasize-max=infinity:\
	:datasize-cur=4096M:\
	:maxproc-max=1024:\
	:maxproc-cur=256:\
	:tc=default:

#
# Override resource limits for certain daemons started by rc.d(8)
#
bgpd:\
	:openfiles-cur=512:\
	:tc=daemon:

unbound:\
	:openfiles-cur=512:\
	:tc=daemon: ' > /etc/login.conf

# configure .profile
echo '
############################################
  Add following lines to your ~/.profile:
    ENV=$HOME/.kshrc
    export ENV'

# configure .kshrc
echo '############################################
  Add following lines to your ~/.kshrc:
    alias ls='ls -F'
    alias poweroff='doas shutdown -h now'
############################################
'

sed -e s/rw/rw,noatime,softdep/ /etc/fstab | tee /etc/fstab
